AWSTemplataFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Simple CRUD Web service. State is stored in DynamoDB table.
Resources:
  GetAverageFunction: #任意の処理名
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.resources
      Runtime: nodejs6.10
      Policies: AmasonDynamoDBReadOnlyAccess
      Environment:
        Variables:
          TABLE_NAME: !Ref Table
      Events: #index.getのトリガー
        GetResource:
          Type: Api
          Properties:
            Path: /resources
            Method: get
  PutAverageFunction: #任意の処理名
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.putResource
      Runtime: nodejs6.10
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME: !Ref Table
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /resources/{id}
            Method: put
Table:
  Type: AWS::Serverless::SimpleTable